@BE_HostAddress = https://localhost:7253

### Đăng ký

POST {{BE_HostAddress}}/api/auth/register

Content-Type: application/json
{
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "123456"
}